Generate a 3x4 NumPy array with random integers between 1 
and 50.  

a. Calculate and print the Mean, Median, and Standard Deviation 
of the array

b. Print the Sum of all elements and the sum of each row.

c. Reshape the 3x4 array into a 2x6 array and print it. 

CO2 
Page 11 of 13 
 
2. Create two (3 * 3) matrices using NumPy and print it. Perform 
and print the results of the following linear algebra operations 
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable) 

# problem 1

In [1]:
import numpy as np

arr= [np.random.randint(1 ,50) for i in range(0,12)]# by using a list comprehension
arr = np.array(arr)## converting it into a numpy array
arr = arr.reshape([3,4])
print(arr)

[[48 29 40 18]
 [14 33 15 37]
 [12 38 48 16]]


##  problem a

In [2]:
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
print(f"mean is: {mean}, median is: {median}, std is: {std}")

mean is: 29.0, median is: 31.0, std is: 12.922847983320086


##  problem b

In [3]:
total = 0
row_sum = 0
list_row_sum  = []
for row in arr:
   
    for row_ele in row:
        total += row_ele
        row_sum += row_ele
   
    list_row_sum.append(row_sum)
    row_sum = 0
        
    
print(f"total sum equals {total}  , the list of sum of the rows is {list_row_sum}")

total sum equals 348  , the list of sum of the rows is [135, 99, 114]


## problem c

In [4]:
arr = arr.reshape(2,6)
print(arr)

[[48 29 40 18 14 33]
 [15 37 12 38 48 16]]


# problem number 2

In [25]:
def matrix_operations(lista , listb):
    print("the first list A that has been entered is\n" , lista)
    print("the second list B that has been entered is\n" , listb)
    print("addition of 2 numpy arrays\n" , lista+listb)
    print("subtraction of 2 numpy arrays\n" , lista - listb)
    print("dot product of 2 matrices\n"  , np.dot(lista,listb))
    print("row wise multiplication is\n" , np.matmul(lista,listb))
    print("transpose of 2 matrices are\n" ,"1st list\n", lista.T ,"\n","2nd list\n", listb.T)
    deta = np.linalg.det(lista)
    detb = np.linalg.det(listb)
    print("determinant of matrix A  is" ,deta )
    print("determinant of matrix B  is" ,detb )
    
    if(deta != 0):
        print("inverse of matrix A is " , np.linalg.inv(lista))
    if(detb != 0):
        print("inverse of matrix B is" , np.linalg.inv(listb))

In [26]:
matrix_operations(np.arange(9).reshape(3,3) , np.arange(2 , 11).reshape(3,3))

the first list A that has been entered is
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
the second list B that has been entered is
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
addition of 2 numpy arrays
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
subtraction of 2 numpy arrays
 [[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]
dot product of 2 matrices
 [[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
row wise multiplication is
 [[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
transpose of 2 matrices are
 1st list
 [[0 3 6]
 [1 4 7]
 [2 5 8]] 
 2nd list
 [[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]
determinant of matrix A  is 0.0
determinant of matrix B  is 0.0


# magic square

In [51]:
def is_magic_square(square):
    n = len(square)
    sum_diag1 = sum(square[i][i] for i in range(n))
    sum_diag2 = sum(square[i][n-1-i] for i in range(n))
    
    if sum_diag1 != sum_diag2:
        return False
    
    for i in range(n):
        if sum(square[i]) != sum_diag1:
            return False
        if sum(square[j][i] for j in range(n)) != sum_diag1:
            return False
    
    return True

square = [
    [8, 1, 6],
    [3, 5, 7],
    [4, 9, 2]
]

print(is_magic_square(square))


True


In [80]:
LISTA = [1,5,6,7,8,10]
LISTB = [2,3,4 , 9]
pos = 0
for i in range(0 , len(LISTA)):
    if pos == len(LISTB)-1:
            pos= pos
    else:
        pos += 1
    print(i)
    print(pos)
    if LISTB[pos] >  LISTA[i] and LISTB[pos] < LISTA[i+1]:
        
        LISTA.insert(LISTA[i] , LISTB[pos])
        print("yes")
        


        
LISTA

0
1
yes
1
2
yes
2
3
3
3
4
3
5
3


[1, 3, 5, 4, 6, 7, 8, 10]